<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Curriculum Vitae</title>
    <style>
        body {
            background-color: #F1F2FA;
        }
        h1, pre {
            text-align: center;
        }
        h2, pre {
            padding: 10px;
            display: inline;
        }
        a {
            text-decoration: none;
            font-size: 12px;
            padding: 6px;
            display: inline-block;
            border-radius: 10px;
        }
        a:link {
            background-color: #B5FCB6;
            color: green;
        }
        a:visited {
            background-color: #EE77F6;
            color: white;
        }
        a:hover {
            background-color: #F6F655
        }
        a:active {
            background-color: palevioletred;
        }
    </style>
</head>
<body>
    <h1>Dariush Ghaemi</h1>
    <pre>Tel: +989399747948 | Email: ghaemye@gmail.com | in: dariush-ghaemi-00705a227</pre>
    <h2>Research Interests</h2>
    <pre><b>Information Theory, Image Processing, Machine Learning, Data Science, Optimization</b></pre>
    <!-- Education Section -->
    <h2>Education</h2>
    <!-- Sharif University of Technology -->
    <pre>
<b>Sharif University of Technology</b>                                                                                                                         Sep. 2019 - Present  
BSc in Electrical Engineering
Current GPA: 17.82/20
    </pre>
    <!-- Allameh Helli High School -->
    <pre>
<b>Allameh Helli High School</b>                                                                                                                             Sep. 2016 - Jun. 2019
Diploma in Physics and Mathematics
GPA: 19.63/20
    </pre>
    <!-- Research Projects Section -->
    <h2>Research Projects</h2>
    <!-- Project Details -->
    <pre><b>Design and Implementation of Distributed Dimensionality Reduction Algorithms Under Communication Constraints</b>                                                                                                                               Jun. 2023 - Present
Research Project, Advisor: Prof. M. H. Yassaee
• The problem can be interpreted as covariance matrix estimation.
• I’m currently trying to provide a tight bound for estimation error.
<b>Quality Control of a Screw Production Line using Computer Vision</b>                                                                                      Jul. 2022 - May. 2023
BS Project, Advisor: Prof. M. Hashemi
• Designed and implemented a screw detection algorithm (edge detection), then extracted screw features to check them.
• Designed and implemented a template matching algorithm to check the validity of the screw
• Ran the algorithms real-time using a camera
<b>Research on Regret-bounds and Information-Theoretic limits in No-Regret Algorithms</b>                                                                    Oct. 2021 - Feb. 2022
Course Project, Advisor: Prof. M. H. Yassaee
• Read several journal papers and books, including Bandit Algorithms by Csaba Szepesvari and Tor Lattimore</pre>
    <!-- Work Experience Section -->
    <h2>Work Experience</h2>
    <!-- Work Details -->
    <pre><b>Computer Vision Engineer</b>                                                                                                                               Mar. 2022 - May 2023
RetinaTech<a href="https://retina.tech/"> Link</a>
• Quality Control using computer vision in industry
• 12 hours per week (20 hours per week in summer)
<b>Teaching Assistantship</b>                                                                                                                                  Sep. 2021 - Present
Sharif University of Technology
• Engineering Mathematics (Fall 2021): Designing and grading homework and quizzes
• Probability and Statistics (Fall 2022): Designing homework and the end-of-class project; Tutoring
• 5 hours per week in each semester
<b>Secondary School Teacher and Curriculum Advisor</b>                                                                                                       Jun. 2019 - Sep. 2021
Allameh Helli High School
• 15 hours per week in each semester
