<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Curriculum Vitae</title>
    <style>
        h1, pre {
            text-align: center;
        }
        h2, pre {
            padding: 10px;
            display: inline;
        }
        a:link {
            text-decoration: none;
            background-color: #B5FCB6;
            color: green;
            font-size: 12px;
            padding: 6px;
            display: inline-block;
            border-radius: 10px;
        }
        a:visited {
            background-color: #EE77F6;
            color: white;
            font-size: 12px;
        }
        a:hover {
            background-color: #F6F655
        }
        a:active {
            background-color: palevioletred;
        }
    </style>
</head>
<body style="background-color:#F1F2FA;">
    <h1>Dariush Ghaemi</h1>
    <pre> Tel: +989399747948 | Email: ghaemye@gmail.com | in:  dariush-ghaemi-00705a227</pre>
    <h2>Research Interests</h2>
    <pre><b>Information Theory, Image Processing, Machine Learning, Data Science, Optimization</b></pre>
    <!-- Rest of your HTML content -->
</body> 
</html>
